"""California county metadata shared by court/county features."""

CALIFORNIA_COUNTIES = [
    {'slug': 'alameda', 'name': 'Alameda'},
    {'slug': 'alpine', 'name': 'Alpine'},
    {'slug': 'amador', 'name': 'Amador'},
    {'slug': 'butte', 'name': 'Butte'},
    {'slug': 'calaveras', 'name': 'Calaveras'},
    {'slug': 'colusa', 'name': 'Colusa'},
    {'slug': 'contra-costa', 'name': 'Contra Costa'},
    {'slug': 'del-norte', 'name': 'Del Norte'},
    {'slug': 'el-dorado', 'name': 'El Dorado'},
    {'slug': 'fresno', 'name': 'Fresno'},
    {'slug': 'glenn', 'name': 'Glenn'},
    {'slug': 'humboldt', 'name': 'Humboldt'},
    {'slug': 'imperial', 'name': 'Imperial'},
    {'slug': 'inyo', 'name': 'Inyo'},
    {'slug': 'kern', 'name': 'Kern'},
    {'slug': 'kings', 'name': 'Kings'},
    {'slug': 'lake', 'name': 'Lake'},
    {'slug': 'lassen', 'name': 'Lassen'},
    {'slug': 'los-angeles', 'name': 'Los Angeles'},
    {'slug': 'madera', 'name': 'Madera'},
    {'slug': 'marin', 'name': 'Marin'},
    {'slug': 'mariposa', 'name': 'Mariposa'},
    {'slug': 'mendocino', 'name': 'Mendocino'},
    {'slug': 'merced', 'name': 'Merced'},
    {'slug': 'modoc', 'name': 'Modoc'},
    {'slug': 'mono', 'name': 'Mono'},
    {'slug': 'monterey', 'name': 'Monterey'},
    {'slug': 'napa', 'name': 'Napa'},
    {'slug': 'nevada', 'name': 'Nevada'},
    {'slug': 'orange', 'name': 'Orange'},
    {'slug': 'placer', 'name': 'Placer'},
    {'slug': 'plumas', 'name': 'Plumas'},
    {'slug': 'riverside', 'name': 'Riverside'},
    {'slug': 'sacramento', 'name': 'Sacramento'},
    {'slug': 'san-benito', 'name': 'San Benito'},
    {'slug': 'san-bernardino', 'name': 'San Bernardino'},
    {'slug': 'san-diego', 'name': 'San Diego'},
    {'slug': 'san-francisco', 'name': 'San Francisco'},
    {'slug': 'san-joaquin', 'name': 'San Joaquin'},
    {'slug': 'san-luis-obispo', 'name': 'San Luis Obispo'},
    {'slug': 'san-mateo', 'name': 'San Mateo'},
    {'slug': 'santa-barbara', 'name': 'Santa Barbara'},
    {'slug': 'santa-clara', 'name': 'Santa Clara'},
    {'slug': 'santa-cruz', 'name': 'Santa Cruz'},
    {'slug': 'shasta', 'name': 'Shasta'},
    {'slug': 'sierra', 'name': 'Sierra'},
    {'slug': 'siskiyou', 'name': 'Siskiyou'},
    {'slug': 'solano', 'name': 'Solano'},
    {'slug': 'sonoma', 'name': 'Sonoma'},
    {'slug': 'stanislaus', 'name': 'Stanislaus'},
    {'slug': 'sutter', 'name': 'Sutter'},
    {'slug': 'tehama', 'name': 'Tehama'},
    {'slug': 'trinity', 'name': 'Trinity'},
    {'slug': 'tulare', 'name': 'Tulare'},
    {'slug': 'tuolumne', 'name': 'Tuolumne'},
    {'slug': 'ventura', 'name': 'Ventura'},
    {'slug': 'yolo', 'name': 'Yolo'},
    {'slug': 'yuba', 'name': 'Yuba'},
]

