"""Seed the database with VERIFIED Humboldt County pickleball courts.
Sources: playtimescheduler.com, pickleballarcata.com, bounce.game, cityofarcata.org
"""
from backend.app import db
from backend.models import Court
from backend.services.court_payloads import normalize_court_payload

# Only verified courts with real addresses and accurate coordinates
HUMBOLDT_COURTS = [
    {
        "name": "McKinleyville Activity Center",
        "description": "Indoor dedicated pickleball courts with permanent lines and portable nets.",
        "address": "1705 Gwin Rd",
        "city": "McKinleyville",
        "state": "CA",
        "zip_code": "95519",
        "latitude": 40.942647,
        "longitude": -124.098424,
        "indoor": True,
        "lighted": True,
        "num_courts": 3,
        "surface_type": "Wood",
        "hours": "Daily 7am-10pm",
        "open_play_schedule": "",
        "fees": "Drop-in fee required",
        "phone": "(707) 839-3251",
        "website": "https://www.mckinleyvillecsd.com",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": True,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": True,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "shared",
        "verified": False
    },
    {
        "name": "Carlson Park",
        "description": "Outdoor dedicated pickleball courts with permanent lines and nets. Free to play.",
        "address": "5201 Carlson Park Drive",
        "city": "Arcata",
        "state": "CA",
        "zip_code": "95521",
        "latitude": 40.9059591,
        "longitude": -124.0774212,
        "indoor": False,
        "lighted": False,
        "num_courts": 3,
        "surface_type": "Concrete",
        "hours": "Daily sunrise to sunset",
        "open_play_schedule": "",
        "fees": "Free",
        "phone": "",
        "website": "",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": True,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": True,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "dedicated",
        "verified": False
    },
    {
        "name": "Larson Park",
        "description": "Outdoor dedicated pickleball courts with permanent lines. Free to play, with lighting and amenities.",
        "address": "901 Grant Avenue",
        "city": "Arcata",
        "state": "CA",
        "zip_code": "95521",
        "latitude": 40.881025,
        "longitude": -124.083248,
        "indoor": False,
        "lighted": True,
        "num_courts": 3,
        "surface_type": "Concrete",
        "hours": "Daily sunrise to sunset",
        "open_play_schedule": "",
        "fees": "Free",
        "phone": "",
        "website": "",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": True,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": False,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "dedicated",
        "verified": False
    },
    {
        "name": "Cal Poly Humboldt Forbes Complex (East Gym)",
        "description": "Indoor dedicated pickleball courts with permanent lines and portable nets. Requires fee for use.",
        "address": "Forbes Complex, Union Street",
        "city": "Arcata",
        "state": "CA",
        "zip_code": "95521",
        "latitude": 40.8751712,
        "longitude": -124.0758287,
        "indoor": True,
        "lighted": True,
        "num_courts": 4,
        "surface_type": "Wood",
        "hours": "By reservation",
        "open_play_schedule": "",
        "fees": "One-time fee required",
        "phone": "",
        "website": "https://www.humboldt.edu",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": True,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "shared",
        "verified": False
    },
    {
        "name": "Arcata Community Center",
        "description": "Indoor pickleball courts (bring your own net) at Arcata Community Center. Requires drop-in fee.",
        "address": "321 Dr MLK Jr Parkway",
        "city": "Arcata",
        "state": "CA",
        "zip_code": "95521",
        "latitude": 40.864093,
        "longitude": -124.079757,
        "indoor": True,
        "lighted": True,
        "num_courts": 3,
        "surface_type": "Wood",
        "hours": "Daily 8am-9pm",
        "open_play_schedule": "",
        "fees": "One-time fee required",
        "phone": "(707) 822-7091",
        "website": "https://www.cityofarcata.org",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": False,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": False,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "shared",
        "verified": False
    },
    {
        "name": "Blue Lake Roller Rink",
        "description": "Indoor pickleball courts at Blue Lake Roller Rink (Prasch Hall). 3 courts, with lights and amenities. Fee required.",
        "address": "312 S Railroad Ave",
        "city": "Blue Lake",
        "state": "CA",
        "zip_code": "95525",
        "latitude": 40.8819164,
        "longitude": -123.9930057,
        "indoor": True,
        "lighted": True,
        "num_courts": 3,
        "surface_type": "Wood",
        "hours": "Tue 5pm-8pm (rec nights)",
        "open_play_schedule": "",
        "fees": "Drop-in fee required",
        "phone": "(707) 668-5655",
        "website": "https://bluelake.ca.gov",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": True,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": True,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "dedicated",
        "verified": False
    },
    {
        "name": "Blue Lake Tennis Courts",
        "description": "Outdoor pickleball courts at Gymkhana Field (210 Chartin Rd). Tennis courts converted with permanent pickleball lines. Free to play.",
        "address": "210 Chartin Road",
        "city": "Blue Lake",
        "state": "CA",
        "zip_code": "95525",
        "latitude": 40.8806007,
        "longitude": -123.9922411,
        "indoor": False,
        "lighted": False,
        "num_courts": 4,
        "surface_type": "Asphalt",
        "hours": "Daily sunrise to sunset",
        "open_play_schedule": "",
        "fees": "Free",
        "phone": "",
        "website": "",
        "email": "",
        "photo_url": "",
        "has_restrooms": False,
        "has_parking": True,
        "has_water": False,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": False,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "converted",
        "verified": False
    },
    {
        "name": "Adorni Center",
        "description": "Indoor pickleball courts at Adorni Center. 4 courts available (multi-use gym). Drop-in fee required.",
        "address": "1011 Waterfront Drive",
        "city": "Eureka",
        "state": "CA",
        "zip_code": "95501",
        "latitude": 40.80611,
        "longitude": -124.15972,
        "indoor": True,
        "lighted": True,
        "num_courts": 4,
        "surface_type": "Wood",
        "hours": "Daily 9am-9pm",
        "open_play_schedule": "",
        "fees": "Drop-in fee required",
        "phone": "(707) 441-4248",
        "website": "https://www.eurekaca.gov/639/Adorni-Center",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": True,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "shared",
        "verified": False
    },
    {
        "name": "Highland Park",
        "description": "Outdoor pickleball courts at Highland Park, Eureka. 8 courts with permanent lines, free to play.",
        "address": "1206 Highland Avenue",
        "city": "Eureka",
        "state": "CA",
        "zip_code": "95503",
        "latitude": 40.7758857,
        "longitude": -124.1845048,
        "indoor": False,
        "lighted": True,
        "num_courts": 8,
        "surface_type": "Concrete",
        "hours": "Daily sunrise to sunset",
        "open_play_schedule": "",
        "fees": "Free",
        "phone": "",
        "website": "",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": False,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": False,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "dedicated",
        "verified": False
    },
    {
        "name": "College of the Redwoods",
        "description": "Outdoor pickleball courts at College of the Redwoods, Eureka. 8 courts, free to play with lights.",
        "address": "7351 Tompkins Hill Road",
        "city": "Eureka",
        "state": "CA",
        "zip_code": "95501",
        "latitude": 40.6952404,
        "longitude": -124.1980561,
        "indoor": False,
        "lighted": True,
        "num_courts": 8,
        "surface_type": "Asphalt",
        "hours": "Daily sunrise to sunset",
        "open_play_schedule": "",
        "fees": "Free",
        "phone": "(707) 476-4213",
        "website": "https://www.redwoods.edu",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": False,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "dedicated",
        "verified": False
    },
    {
        "name": "Bear River Recreation Center",
        "description": "Indoor pickleball courts at Bear River Recreation Center (Loleta). 4 courts, fee required.",
        "address": "265 Keisner Road",
        "city": "Loleta",
        "state": "CA",
        "zip_code": "95551",
        "latitude": 40.66224,
        "longitude": -124.22269,
        "indoor": True,
        "lighted": True,
        "num_courts": 4,
        "surface_type": "Wood",
        "hours": "Tue/Thu 6pm-8pm (drop-in)",
        "open_play_schedule": "",
        "fees": "Drop-in fee or membership",
        "phone": "(707) 532-0212",
        "website": "https://www.bearriverrecreationcenter.com",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": True,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": True,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "shared",
        "verified": False
    },
    {
        "name": "Rohner Park",
        "description": "Outdoor pickleball courts at Rohner Park (Fortuna). 2 courts with permanent lines. Free to play.",
        "address": "9 Park Street",
        "city": "Fortuna",
        "state": "CA",
        "zip_code": "95540",
        "latitude": 40.6014421,
        "longitude": -124.1504215,
        "indoor": False,
        "lighted": False,
        "num_courts": 2,
        "surface_type": "Concrete",
        "hours": "Daily sunrise to sunset",
        "open_play_schedule": "",
        "fees": "Free",
        "phone": "",
        "website": "https://www.friendlyfortuna.com",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": False,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "dedicated",
        "verified": False
    },
    {
        "name": "Fortuna Skating Rink",
        "description": "Indoor pickleball courts at Fortuna Skating Rink (Firemen's Pavilion). 3 courts, one-time fee required.",
        "address": "9 Park Street",
        "city": "Fortuna",
        "state": "CA",
        "zip_code": "95540",
        "latitude": 40.600648,
        "longitude": -124.1492225,
        "indoor": True,
        "lighted": True,
        "num_courts": 3,
        "surface_type": "Wood",
        "hours": "Fri 6pm-9pm",
        "open_play_schedule": "",
        "fees": "$3 drop-in per session",
        "phone": "(707) 725-7620",
        "website": "https://www.friendlyfortuna.com",
        "email": "",
        "photo_url": "",
        "has_restrooms": True,
        "has_parking": True,
        "has_water": False,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": True,
        "nets_provided": True,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "shared",
        "verified": False
    },
    {
        "name": "Shelter Cove",
        "description": "Outdoor pickleball courts in Shelter Cove. 3 asphalt courts with permanent lines on Upper Pacific Drive, free to play.",
        "address": "389 Upper Pacific Drive",
        "city": "Shelter Cove",
        "state": "CA",
        "zip_code": "95589",
        "latitude": 40.038207,
        "longitude": -124.070087,
        "indoor": False,
        "lighted": False,
        "num_courts": 3,
        "surface_type": "Asphalt",
        "hours": "Daily sunrise to sunset",
        "open_play_schedule": "",
        "fees": "Free",
        "phone": "",
        "website": "",
        "email": "",
        "photo_url": "",
        "has_restrooms": False,
        "has_parking": True,
        "has_water": False,
        "has_pro_shop": False,
        "has_ball_machine": False,
        "wheelchair_accessible": False,
        "nets_provided": False,
        "paddle_rental": False,
        "skill_levels": "all",
        "court_type": "converted",
        "verified": False
    }
]


def seed_courts():
    """Insert verified Humboldt County courts if the database is empty."""
    if Court.query.first():
        return 0

    count = 0
    for court_data in HUMBOLDT_COURTS:
        normalized_data = dict(court_data)
        normalized_data['state'] = 'CA'
        normalized_data, errors = normalize_court_payload(normalized_data, partial=False)
        if errors:
            raise ValueError(f'Invalid seeded court payload for {court_data.get("name", "unknown")}: {errors}')

        court = Court(**normalized_data)
        db.session.add(court)
        count += 1

    db.session.commit()
    return count
