import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { brotliCompressSync, constants, gzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { build } from 'esbuild';
import { minify } from 'terser';

const release = 'r68';
const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = path.join(projectRoot, 'public');
const outputDir = path.join(publicDir, 'assets', release);
const entries = [
  ['app-v15.js', 'app-v15.min.js'],
  ['crew-planner-v15.js', 'crew-planner-v15.min.js'],
  ['styles-v15.css', 'styles-v15.min.css'],
];

const digest = (contents) => createHash('sha256').update(contents).digest('hex');

// This directory contains generated bytes for one explicit release only. A
// clean rebuild prevents an old filename from being deployed accidentally.
await rm(outputDir, { recursive: true, force: true });
await mkdir(outputDir, { recursive: true });

const files = {};
for (const [sourceName, outputName] of entries) {
  const sourcePath = path.join(publicDir, sourceName);
  const outputPath = path.join(outputDir, outputName);
  const source = await readFile(sourcePath);
  if (sourceName.endsWith('.js')) {
    // Terser's cross-statement compression keeps the monolithic application
    // under the release's 250 KiB Brotli budget.  Use a stable relative source
    // name so source maps remain deterministic across machines/workspaces.
    const mappedSourceName = path.relative(outputDir, sourcePath)
      .split(path.sep).join('/');
    const result = await minify(
      { [mappedSourceName]: source.toString('utf8') },
      {
        ecma: 2020,
        compress: true,
        mangle: true,
        format: { comments: false, ecma: 2020 },
        sourceMap: {
          filename: outputName,
          includeSources: true,
        },
      },
    );
    if (!result.code || !result.map) {
      throw new Error(`Terser did not emit code and a source map for ${sourceName}`);
    }
    await Promise.all([
      writeFile(outputPath, `${result.code}\n`),
      writeFile(`${outputPath}.map`, `${result.map}\n`),
    ]);
  } else {
    await build({
      entryPoints: [sourcePath],
      outfile: outputPath,
      bundle: false,
      minify: true,
      sourcemap: 'external',
      sourcesContent: true,
      legalComments: 'none',
      charset: 'utf8',
      logLevel: 'warning',
    });
  }
  const output = await readFile(outputPath);
  const gzip = gzipSync(output, { level: 9, mtime: 0 });
  // zlib stamps its platform in the gzip OS header byte (Darwin=19,
  // Unix=3), even when the deflate payload is otherwise identical. Normalize
  // it so macOS development and Linux CI emit the same committed artifact.
  gzip[9] = 255;
  const brotli = brotliCompressSync(output, {
    params: {
      [constants.BROTLI_PARAM_QUALITY]: 11,
      [constants.BROTLI_PARAM_MODE]: sourceName.endsWith('.css')
        ? constants.BROTLI_MODE_TEXT : constants.BROTLI_MODE_TEXT,
    },
  });
  await Promise.all([
    writeFile(`${outputPath}.gz`, gzip),
    writeFile(`${outputPath}.br`, brotli),
  ]);
  files[outputName] = {
    source: sourceName,
    source_sha256: digest(source),
    source_bytes: source.length,
    minified_bytes: output.length,
    gzip_bytes: gzip.length,
    brotli_bytes: brotli.length,
  };
}

await writeFile(
  path.join(outputDir, 'manifest.json'),
  `${JSON.stringify({ release, files }, null, 2)}\n`,
);
